#!/usr/bin/env zsh
# NixOS package search (unstable) via lynx
query="${*// /+}"
exec lynx "https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=${query}"
