set-option -g prefix C-b
bind-key C-b send-prefix
# theme
source-file "${HOME}/skel/tmux/themes/powerline/block/green.tmuxtheme"
# install `tpm` if needed.
# if "test ! -d ~/.tmux/plugins/tpm" \
#    "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
# plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jabirali/tmux-tilish'
set -g @tilish-default 'main-vertical'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'laktak/extrakto'
# set -g @plugin 'tmux-plugins/tmux-logging'
# set -g @logging-path '/var/log/tmux'
# set -g @logging-filename "%Y-%m-%d_#{session_name}-#{window_index}-#{pane_index}.log"

set -g extended-keys on
# start window numbers at 1 rather than 0.
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
setw -g alternate-screen on
set-option -g renumber-windows on
#set-option -sa terminal-overrides ",xterm*,Tc"
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",alacritty:Tc"
# set -g default-terminal "alacritty"
set -ga terminal-overrides ",xterm-256color:Tc"
set -as terminal-features ",alacritty:clipboard"
set -g set-clipboard on
# be notified when something happens inside other windows
setw -g monitor-activity on
set -g visual-activity off
set -g status-position bottom
set -g status-justify center
set-option -g status-interval 5
set-window-option -g aggressive-resize off
set-option -s escape-time 0
set-option -g focus-events on
set-option -g display-time 4000
set-option -g history-limit 50000
# ensure 'xclip' or 'xsel' is installed on your system
set-option -g set-clipboard on
## vi
set -g mode-keys vi
set -g status-keys vi
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1
# avoid cursor movement messing with resize
set -g repeat-time 800

# splits
#bind -r v split-window -h -c "#{pane_current_path}"
#bind -r c split-window -v -c "#{pane_current_path}"

# window movement
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# reload the config.
bind R source-file ~/.tmux.conf \; display "reloaded ~/.tmux.conf"

unbind -T copy-mode MouseDrag1Pane
unbind -T copy-mode-vi MouseDrag1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane
# Copy selection to system clipboard
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
# Ensure that we can use the mouse to select text without shift in Alacritty
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# unbind keys to not conflict w/ helix-editor bindings
unbind-key -T root M-n
unbind-key M-n
unbind-key -T root M-p
unbind-key M-p
unbind-key -T root M-s
## Unbind C-i from all tables
unbind -n C-i
unbind -T prefix C-i
unbind -T root C-i
unbind -T copy-mode C-i
unbind -T copy-mode-vi C-i

# Disable aggressive resize
set-window-option -g aggressive-resize off
# Prevent automatic window renaming
set-window-option -g automatic-rename off
# Maintain window size
set-window-option -g window-size smallest

bind-key -T prefix C-u copy-mode \; send-keys scroll-up
# bind-key -T prefix C-u copy-mode \; send-keys page-up

# window navigation
bind-key -n C-M-p previous-window
bind-key -n C-M-n next-window
