set-option -g prefix C-b
bind-key C-b send-prefix

set -g mouse on
set -g extended-keys on
set -g base-index 1
setw -g pane-base-index 1
setw -g alternate-screen on
set -g renumber-windows on
set -g repeat-time 800

# theme
source-file "${HOME}/skel/tmux/themes/powerline/block/green.tmuxtheme"

# install `tpm` if needed.
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# plugins 
set -g @plugin 'jabirali/tmux-tilish'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
# set -g @plugin 'tmux-plugins/tmux-logging'
# plugin options
set -g @tilish-default 'main-vertical'
set -g @tilish-enforce 'none'
set -g @tilish-createauto 'off'
# set -g @logging-path '/var/log/tmux'
# set -g @logging-filename "%Y-%m-%d_#{session_name}-#{window_index}-#{pane_index}.log"

# activate plugins
run '~/.tmux/plugins/tpm/tpm'

set -g default-terminal "xterm-256color"
# set -g default-terminal "alacritty"
set-option -ga terminal-overrides ",alacritty:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"
set -as terminal-features ",alacritty:clipboard"

# be notified when something happens inside other windows
setw -g monitor-activity on
set -g visual-activity off
set -g status-position bottom
set -g status-justify center
set -g status-interval 5

# ensure 'xclip' or 'xsel' is installed on your system
set -g set-clipboard on

## vi
set -g mode-keys vi
set -g status-keys vi
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# window nav
bind-key -n C-M-h previous-window
bind-key -n C-M-l next-window
# window swap
bind -n C-S-Left swap-window -t -1\; select-window -t -1
bind -n C-S-Right swap-window -t +1\; select-window -t +1

unbind -T copy-mode MouseDrag1Pane
unbind -T copy-mode-vi MouseDrag1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane
# Copy selection to system clipboard
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
# Ensure that we can use the mouse to select text without shift in Alacritty
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# unbind keys to not conflict w/ helix-editor bindings
unbind-key -T root M-n
unbind-key M-n
unbind-key -T root M-p
unbind-key M-p
unbind-key -T root M-s
## Unbind C-i from all tables
unbind -n C-i
unbind -T prefix C-i
unbind -T root C-i
unbind -T copy-mode C-i
unbind -T copy-mode-vi C-i

bind-key -T prefix C-u copy-mode \; send-keys scroll-up
# bind-key -T prefix C-u copy-mode \; send-keys page-up
